
name: Check Python requirements

on:
  push:
    branches:
      - main

jobs:
  check-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Choose a version that works

      - name: Install dependencies
        run: |
          sudo apt-get install python3-distutils
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check for changes
        id: check
        run: |
          INSTALLED_MATPLOTLIB_VERSION=$(pip freeze | grep -E '^matplotlib==' | cut -d'=' -f 3)
          SAVED_MATPLOTLIB_VERSION=$(grep -E '^matplotlib==' requirements_snapshot.txt | cut -d'=' -f 3)
          if [ "$INSTALLED_MATPLOTLIB_VERSION" == "$SAVED_MATPLOTLIB_VERSION" ]; then
            echo "Matplotlib version is up to date: $INSTALLED_MATPLOTLIB_VERSION"
          else
            echo "Matplotlib version has changed from $SAVED_MATPLOTLIB_VERSION to $INSTALLED_MATPLOTLIB_VERSION"
            echo "matplotlib==$INSTALLED_MATPLOTLIB_VERSION" > requirements_snapshot.txt
            # Add any additional steps for notification here
          fi
