name: Check Python requirements

on:
  push:
    branches:
      - main

jobs:
  check-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Choose a version that works

      - name: Install dependencies
        run: |
          sudo apt-get install python3-distutils
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check for changes
        id: check
        run: |
          INSTALLED_PACKAGES=$(pip freeze)

          if diff -u <(echo "$INSTALLED_PACKAGES") <(cat requirements_snapshot.txt); then
            echo "Requirements are up to date."
          else
            echo "Requirements have changed!"
            echo "$INSTALLED_PACKAGES" > requirements_snapshot.txt
            # Add any additional steps for notification here
          fi
